name: Build rexglue-sdk win-amd64

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  actions: write

jobs:
  build:
    uses: ./.github/workflows/_build-platform.yaml
    with:
      platform: win-amd64
      ref: ${{ github.ref }}
      publish_mode: release
      extra_cmake_args: -DREXGLUE_USE_VULKAN=ON
    secrets: inherit
